### ISSUE TITLE
how to call mathjax in a new converter

### ISSUE THREAD

**Issue by fardina** [szego/pagedown-mathjax-example#2]
Hi
At first thank you for your great work.
I need to create a new converter like this:

```
var converter1 = new Markdown.Converter();
document.getElementById("'."wmd-preview-".$fieldname.'").innerHTML =  converter1.makeHtml(document.getElementById("'."wmd-input-".$fieldname.'").value);
```

When I was using this script (https://github.com/mathjax/MathJax/blob/master/test/sample-dynamic-2.html) I was calling Preview.Update(); at the end of above code for rendering math:

```
var converter1 = new Markdown.Converter();
            document.getElementById("'."wmd-preview-".$fieldname.'").innerHTML = converter1.makeHtml(document.getElementById("'."wmd-input-".$fieldname.'").value);Preview.Update();
```

But now I don't know which function doing the same. Could you help please? I tried `mjpd.Editing.UpdateMJ();` but it seems doesn't work for me.

**Comment by szego** [comment]
Hi fardina,

It seems like you should also be creating a new Markdown.Editor object associated with the wmd-input-... textarea and also a new MJPD object. Then you can call
- the Editing.prepareWmdForMathJax() method of the MJPD object to give the Markdown.Converter and Markdown.Editor objects the right callbacks to render MathJax and
- the  .run() method of the Editor object to start updating the wmd-preview-... div.

I'm not sure I understand your code example. Does the following fit your needs? I assume that fieldname (from your code) is a string.

``` javascript
var converter1 = new Markdown.Converter();
var editor1 = new Markdown.Editor(converter1, '-' + fieldname);
var mjpd1 = new MJPD();
mjpd1.Editing.prepareWmdForMathJax(editor1, '-' + fieldname, [["$", "$"]]);
editor1.run();
```

**Comment by fardina** [comment]
Thank you for your quick response.
This works fine. But everytime I click on the buttons it creates a new button bar.

I am using this version of markdown editor(https://github.com/thibaultduponchelle/q2a-markdown-editor-latex/blob/master/foleef_functions.js) in my forum website which writes the latex commands by clicking on the images.
I tried render mathjax after clicking on these images by adding this function:
```
function updatemathjax(){
var converter1 = new Markdown.Converter();
var editor1 = new Markdown.Editor(converter1, '-' + fieldname);
var mjpd1 = new MJPD();
mjpd1.Editing.prepareWmdForMathJax(editor1, '-' + fieldname, [["$", "$"]]);
editor1.run();
}
```
to
```
$(".iSymbol a").click(function(e) {
						latex = $(this).attr("title");
						$(".wmd-input").insertAtCaret(" $"+latex+"$ ");
                                                 updatemathjax();
						e.preventDefault();					
					});
```
This works But after clicking on images it generates a new button bar(B,I,link,quote,code,image, list,..).

**Comment by szego** [comment]
You should not be creating new Converter, Editor, and MJPD objects whenever you want the preview to update. In fact you do not need a function like updatemathjax() at all, and this example doesn't use one, since the updating is handled by the Editor object.

You seem to be trying to do things in a way that is very different from the way it is done in this example. Perhaps if you review the code for it again, it might be more clear what's going on? I'm going to close this issue, but please feel free to email me if you have any questions about how the code for this example works.
